version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive
    - misspell
    - unused
    - gocritic
    - bodyclose
    - gosec
    - unconvert
    - copyloopvar
    - durationcheck
    - prealloc
    - whitespace
    - dogsled
    - asciicheck
    - nilerr

formatters:
  enable:
    - gofmt
    - gofumpt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m